In [1]:
from sklearn import metrics
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
dataset=datasets.load_iris()
model=GaussianNB()
model.fit(dataset.data,dataset.target)
expected=dataset.target
predicted=model.predict(dataset.data)
print("Accuracy:",accuracy_score(expected,predicted))
print("Classification Report:\n",metrics.classification_report(expected,predicted))
print("Confusion Matrix:\n",metrics.confusion_matrix(expected,predicted))

Accuracy: 0.96
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.94      0.94        50
           2       0.94      0.94      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150

Confusion Matrix:
 [[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]


In [2]:
import sklearn.datasets as ds
import pandas as pd
import numpy as np
from sklearn import preprocessing, neighbors

from sklearn.model_selection import train_test_split
iris = ds.load_iris()
df = pd.DataFrame(iris.data,columns = iris.feature_names)
print(df)
df['species'] = iris.target
print(df)
x = np.array(df.iloc[:,0:-1])
y = np.array(df['species'])
print(x)
print(y)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
clf = neighbors.KNeighborsClassifier()
clf.fit(x_train,y_train)
accuracy = clf.score(x_test,y_test)
print("Accuracy = ",accuracy)

#example_measures = np.array([[4.7,3.2,2,0.2],[5.1,2.4,4.3,0.3]])
prediction = clf.predict(x_test)
#print("Prediction = ",prediction)

df_test = pd.DataFrame(x_test,columns = iris.feature_names)
df_test['species'] = y_test
df_test['prediction'] = prediction

s = np.array(df_test['species'])
p = np.array(df_test['prediction'])

classified = list()
for i in range(len(x_test)):
    if s[i] == p[i]:
        classified.append('correct')
    else:
        classified.append('wrong')

df_test['classified'] = classified
print(df_test)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]
     sepal length (cm)  sepal width (cm)